### ISSUE TITLE
[bug] The rest of the GUI disappears when opening a menu (VSCode)

### ISSUE THREAD

**Issue by eascarrunz** [tldraw/tldraw-v1#10]
Like this:

![tldr_bug](https://user-images.githubusercontent.com/12952668/230363208-c316232d-c127-43ab-9e94-84681185741d.gif)

tldraw v1.28.2, VSCode v1.77.1. Tried on different machines with Windows and Linux.

**Comment by steveruizok** [comment]
Hi, this should be fixed.
