### ISSUE TITLE
[feature] Support any type of medias (oEmbed ?)

### ISSUE THREAD

**Issue by gordielachance** [tldraw/tldraw-v1#115]
Hello, it would be awesome to be able to upload/embed not only images, but also videos or sounds (through [Oembed](https://oembed.com/) ?)!
I use tldraw as a whiteboard and I miss this feature...

Thanks a lot !

**Comment by Atreyu-94** [comment]
Is there any progress here? I am very interested in being able to embed web pages, so that I can add graphics (e.g. Desmos or Geogebra). It would be useful to embed a complete web page and scale it within a frame. But I don't know how hard that is.
