### ISSUE TITLE
[feature] Apple Pencil Support on iPad

### ISSUE THREAD

**Issue by colinfwren** [tldraw/tldraw-v1#202]
> Woe to you, oh earth and sea
> For the Devil sends the feature with wrath
> Because he knows the time is short
> Let him who hath understanding reckon the number of the feature
> For it is a human number
> Its number is six hundred and sixty-six
> 

While it's technically feasible to use the Apple Pencil to draw on the canvas things like palm rejection and pressure sensitivity aren't present, this makes it hard to use the new pressure sensitivity tools from this tweet on iPad.

https://twitter.com/steveruizok/status/1521493624508276737?s=20&t=-nImuXfXAsYgWX3befrUKw

This post would suggest there is a means to get the 'force' of a touch within Safari that should allow for this pressure to be read with the pencil. https://developer.apple.com/forums/thread/31124

**Comment by ashutoshsaboo** [comment]
what's this new repo tldraw-v1, is this repo on route to being archived? I see a separate repo now named as tldraw: https://github.com/tldraw/tldraw/ - wondering if it's some change which has happened recently? @TodePond (atleast i don't personally remember seeing this tldraw-v1 repo earlier, though I might be wrong)

**Comment by ashutoshsaboo** [comment]
thanks for the info, look forward to the blog post! @TodePond
