### ISSUE TITLE
[feature]  Custom data attributes on shapes

### ISSUE THREAD

**Issue by StriveTeam** [tldraw/tldraw-v1#25]
it is not  support custom attributes in shapes? when I selected one shape or line or text , it is excepted to show the username over the shape, but I am not found how to do this. And I cant see the performance and the scenes to be used of 'custom-cursors' component. when should i use it？

**Comment by steveruizok** [comment]
Hi, closing this as we won't be adding new features to this version of tldraw. Check https://github.com/tldraw/tldraw for the latest! I think you'd find the `meta` property helpful there.
