### ISSUE TITLE
[feature] Add some custom functions and how can I rebuild and republish it into npm?

### ISSUE THREAD

**Issue by StriveTeam** [tldraw/tldraw-v1#26]
I have added some custom functions , and I want to rebuild it, and republish it into private npm, but I don't hkow how to rebuild it , I try to exc yarn build  and I replaced the dist folder in my code , but it cant work .... I want to know how to di it

**Comment by steveruizok** [comment]
Closing this, check https://github.com/tldraw/tldraw for the latest! Not sure about build or publish issues, but the comments above should be helpful.
