### ISSUE TITLE
[feature] import/load from json

### ISSUE THREAD

**Issue by no-1ne** [tldraw/tldraw-v1#296]
Ability to export to json/svg is being added in the pull request https://github.com/tldraw/tldraw/pull/468 

It would be great to have the ability to load the exported json. Creating a new issue to track it as suggested by @FarazzShaikh https://github.com/tldraw/tldraw/pull/468#issuecomment-1006611941

Thank you

**Comment by mycroft-cesar** [comment]
any news about this feature?

**Comment by bmitchinson** [comment]
> any news about this feature?

You can now save and load from `.tldr` files, which aren't under the export menu, but are exported by choosing "file > save"

**Comment by lobre** [comment]
Something that does not seem possible yet is to export some part of a project. Let's say I want to select a part of my drawing and reimport it on a different project later.

Can I do that today? The saving to `.tldr` only saves the whole project.
