### ISSUE TITLE
doc.pages is not excepted  in muitiplayer mode

### ISSUE THREAD

**Issue by StriveTeam** [tldraw/tldraw-v1#33]
Steps： 
1. draw line or shape or add text in first page
2. exec app.createPage('XXX')
3. draw line or shape or add text
4. now the content in one page and the wrong position and wrong pages

Looking forward to your reply！！！！Thanks!

**Comment by steveruizok** [comment]
Closing this as we won't be addressing a fix for this version. Check https://github.com/tldraw/tldraw for the latest! And please share there if the bug persists.
