### ISSUE TITLE
[feature] Clickable hyperlinks or URLs in text (or rich text in general)

### ISSUE THREAD

**Issue by goekce** [tldraw/tldraw-v1#4]
If an URL in a text could be converted to a clickable hyperlink, it would be great.

Currently only some shapes support adding links, but these links are only clickable in a very small area. Related: https://github.com/tldraw/tldraw-v1/issues/44

Background info: I use tldraw as part of Bigbluebutton's whiteboard.

**Comment by steveruizok** [comment]
Closing this as we won't be adding new features to this version of tldraw. Check https://github.com/tldraw/tldraw for the latest (which does include this feature!)
