### ISSUE TITLE
[bug] Next.js 13 - Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by milo-** [tldraw/tldraw-v1#42]
Just tried to update to the latest version TLDraw and ran into this error ⬇️

./node_modules/@fontsource/caveat-brush/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@tldraw/tldraw/dist/index.mjs

Import trace for requested module:
./node_modules/@fontsource/caveat-brush/index.css
./node_modules/@tldraw/tldraw/dist/index.mjs

I saw there's already been a discussion around this here https://github.com/tldraw/tldraw/pull/1091 

It's a blocker from us upgrading to the latest version of tldraw

**Comment by TosinHub** [comment]
> Just tried to update to the latest version TLDraw and ran into this error ⬇️
> 
> ./node_modules/@fontsource/caveat-brush/index.css Global CSS cannot be imported from within node_modules. Read more: https://nextjs.org/docs/messages/css-npm Location: node_modules/@tldraw/tldraw/dist/index.mjs
> 
> Import trace for requested module: ./node_modules/@fontsource/caveat-brush/index.css ./node_modules/@tldraw/tldraw/dist/index.mjs
> 
> I saw there's already been a discussion around this here [tldraw/tldraw#1091](https://github.com/tldraw/tldraw/pull/1091)
> 
> It's a blocker from us upgrading to the latest version of tldraw

Have you found a solution to this @milo-

**Comment by steveruizok** [comment]
Closing this as we won't be addressing a fix for this version. I believe this was fixed however. Check https://github.com/tldraw/tldraw for the latest! And please share there if the bug persists.
