### ISSUE TITLE
[feature]Get the picture about only the elements visible within the canvas are obtained, and those beyond the canvas are intercepted

### ISSUE THREAD

**Issue by yangshuo1126** [tldraw/tldraw-v1#5]
If the element or image exceeds the canvas, the generated image will contain the excess part.  We would like to obtain a picture that does not contain any excess parts. 
That is to say, if you want a WYSIWYG image on the canvas and the elements outside the canvas are intercepted, how can add this feature

**Comment by steveruizok** [comment]
Hi, closing this as we won't be adding new features to this version of tldraw. Check https://github.com/tldraw/tldraw for the latest!
