### ISSUE TITLE
[feature] Feature or improvement How will I get the new features?  just like https://beta.tldraw.com/

### ISSUE THREAD

**Issue by xujinglong2021** [tldraw/tldraw-v1#53]
V1.26.3 is the latest version which I download from npmjs.com. Unfortunately,  I found the UI and UX don't change yet, just like https://beta.tldraw.com/ I have to say the beta features are what I want to get. How will I get the new features?  I mean which version should I install locally? Thanks.

**Comment by steveruizok** [comment]
Hi, closing this as we won't be adding new features to this version of tldraw. Check https://github.com/tldraw/tldraw for the latest!
