### ISSUE TITLE
async and package error 

### ISSUE THREAD

**Issue by rajmaskey** [tldraw/tldraw-v1#573]
dev::apps/examples Are they installed?
dev::apps/examples     at file:///workspaces/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:44138:23
dev::apps/examples     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dev::apps/examples     at async file:///workspaces/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:43547:38

**Comment by steveruizok** [comment]
Hi, there's not enough information here to provide an answer.
