### ISSUE TITLE
Share Button

### ISSUE THREAD

**Issue by ajitk19** [tldraw/tldraw-v1#575]
I'm deploying tldraw in my local and checking how it is working. In my local everything is working fine except share option.

kindly help me out from this issue

**Comment by steveruizok** [comment]
Hi, we don't have a share button on this version of tldraw.

You may be looking for the new version of tldraw, https://github.com/tldraw/tldraw. This also does not have a share button, as this functionality is part of the "application layer" we've built around the canvas editor for tldraw.com. This application layer is not open source.
