### ISSUE TITLE
[feature] Ctrl + Click to duplicate a shape

### ISSUE THREAD

**Issue by connorferster** [tldraw/tldraw-v1#6]
A common feature in other drawing programs that folks may be used to using is using `Ctrl + click` to duplicate a shape. Currently, to duplicate a shape, we can do `Ctrl + c`, `Ctrl + v` to copy-paste and the duplicated shape is overlaid on the original shape leaving the success of the copy-paste ambiguous ("Did it do anything?...Oh, wait, yes, I can drag a duplicated shape off").

It would be much faster to be able to just use `Ctrl + click` especially since I think one of the common use cases for the app is drawing flow charts or other diagrams that have repetitive shapes.

Thanks for the consideration!

**Comment by steveruizok** [comment]
Hi, closing this as we won't be adding new features to this version of tldraw. Check https://github.com/tldraw/tldraw for the latest!
