### ISSUE TITLE
[feature] DOT language support

### ISSUE THREAD

**Issue by ayalpani** [tldraw/tldraw-v1#60]
Hi Steve, thanks for tldraw. Did you ever think about supporting DOT Language for automatically creating Graphs?

`$ echo 'digraph { a -> b }' | tldraw > mygraph.tldr`

I believe it would further boost acceptance if it could be used during a developers build process to visualise the project's architecture and processes. After initial build of my tldr file, I would then move things around on the canvas to actually look nice and all changes would somehow be persisted and restored upon opening my tldr file. Something like that:

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/603179/207456999-ac668a36-508d-4ab4-ae7b-7a52ca239b33.png">

https://beta.tldraw.com/r/v2_9UzERvhtDIGIAUniphcvk

**Comment by steveruizok** [comment]
Hi, closing this as we won't be adding new features to this version of tldraw. Check https://github.com/tldraw/tldraw for the latest!
