### ISSUE TITLE
[feature] Double click should start a text entry

### ISSUE THREAD

**Issue by anilgulecha** [tldraw/tldraw-v1#99]
When the mouse is over an empty area (clicking will do nothing) - then a double click in such an area should create a text entry.

This is a small UX change, but uses a easy UI action (doubleclick) and ties it to the most common element in whiteboards (text). This behavior can be seen in excalidraw, and is something that I find very intuitive, and I believe will make tldraw that much better.

**Comment by steveruizok** [comment]
Hi, closing this as we won't be adding new features to this version of tldraw. Check https://github.com/tldraw/tldraw for the latest!
